apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: carmarketplace-dev
spec:
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 8084
      targetPort: 8084