apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: carmarketplace-dev
spec:
  selector:
    app: config-server  
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888