-- insert makes
INSERT INTO make(country, name) VALUES ('USA','FORD')
INSERT INTO make(country, name) VALUES ('Germany','AUDI')
INSERT INTO make(country, name) VALUES ('Germany','BMW')
INSERT INTO make(country, name) VALUES ('Japan','MAZDA')
INSERT INTO make(country, name) VALUES ('Japan','TOYOTA')
INSERT INTO make(country, name) VALUES ('Italy','FERRARI')
INSERT INTO make(country, name) VALUES ('Australia','HOLDEN')
INSERT INTO make(country, name) VALUES ('Japan','HONDA')
INSERT INTO make(country, name) VALUES ('South Korea','HYUNDIA')
INSERT INTO make(country, name) VALUES ('South Korea','KIA')
INSERT INTO make(country, name) VALUES ('Italy','LAMBORGHINI')
INSERT INTO make(country, name) VALUES ('England','LAND ROVER')
INSERT INTO make(country, name) VALUES ('Japan','LEXUS')
INSERT INTO make(country, name) VALUES ('Germany','MERCEDES-BENZ')
INSERT INTO make(country, name) VALUES ('Japan','MITSUBISHI')
INSERT INTO make(country, name) VALUES ('Japan','NISSAN')
INSERT INTO make(country, name) VALUES ('Japan','SUBARU')
INSERT INTO make(country, name) VALUES ('Japan','SUZUKI')
INSERT INTO make(country, name) VALUES ('Germany','VOLKSWAGEN')
INSERT INTO make(country, name) VALUES ('Sweden','VOLVO')

-- insert models

-- FORD
INSERT INTO model(name, type, make_id) VALUES ('Ford Falcon', 'SEDAN',(SELECT id from make WHERE name = 'FORD'))
INSERT INTO model(name, type, make_id) VALUES ('Ford Focus Sedan', 'SEDAN',(SELECT id from make WHERE name = 'FORD'))
INSERT INTO model(name, type, make_id) VALUES ('Ford Focus Hatch', 'HATCHBACK',(SELECT id from make WHERE name = 'FORD'))
INSERT INTO model(name, type, make_id) VALUES ('Ford Puma', 'SUV',(SELECT id from make WHERE name = 'FORD'))
INSERT INTO model(name, type, make_id) VALUES ('Ford Everest', 'SUV',(SELECT id from make WHERE name = 'FORD'))
INSERT INTO model(name, type, make_id) VALUES ('Ford Escape','SUV',(SELECT id from make WHERE name = 'FORD'))
INSERT INTO model(name, type, make_id) VALUES ('Ford Ranger', 'UTE',(SELECT id from make WHERE name = 'FORD'))
--AUDI
INSERT INTO model(name, type, make_id) VALUES ('Audi A4 Sedan', 'SEDAN',(SELECT id from make WHERE name = 'AUDI'))
INSERT INTO model(name, type, make_id) VALUES ('Audi S4 Sedan', 'SEDAN',(SELECT id from make WHERE name = 'AUDI'))
INSERT INTO model(name, type, make_id) VALUES ('Audi A6 Sedan', 'SEDAN',(SELECT id from make WHERE name = 'AUDI'))
INSERT INTO model(name, type, make_id) VALUES ('Audi Q2', 'SUV',(SELECT id from make WHERE name = 'AUDI'))
INSERT INTO model(name, type, make_id) VALUES ('Audi Q3','SUV',(SELECT id from make WHERE name = 'AUDI'))
INSERT INTO model(name, type, make_id) VALUES ('Audi Q5', 'SUV',(SELECT id from make WHERE name = 'AUDI'))
INSERT INTO model(name, type, make_id) VALUES ('Audi Q7', 'SUV',(SELECT id from make WHERE name = 'AUDI'))
INSERT INTO model(name, type, make_id) VALUES ('Audi Q8','SUV',(SELECT id from make WHERE name = 'AUDI'))
INSERT INTO model(name, type, make_id) VALUES ('Audi A1', 'HATCHBACK',(SELECT id from make WHERE name = 'AUDI'))