INSERT INTO make(country, name) VALUES ('USA','FORD')
INSERT INTO make(country, name) VALUES ('GERMANY','AUDI')
INSERT INTO make(country, name) VALUES ('USA','FORD')
INSERT INTO make(country, name) VALUES ('USA','FORD')
INSERT INTO make(country, name) VALUES ('USA','FORD')