apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: carmarketplace-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: cm-apigateway
          image: geekymon2/cm-apigateway:latest
          env:
          - name: ARTIFACT_NAME
            value: "api-gateway"        
          - name: TZ
            value: "Australia/Sydney"
          - name: SPRING_PROFILES_ACTIVE
            value: "ci"
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"