# For troubleshooting only
apiVersion: v1
kind: Pod
metadata:
  name: car-listing-service
  namespace: carmarketplace-dev
spec:
  restartPolicy: Never
  containers:
    - name: car-listing-service
      image: geekymon2/cm-car-listing-svc:latest
      command:
        - sleep
        - "8600"
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      env:
        - name: ARTIFACT_NAME
          value: "car-listing-service"
        - name: CARLISTING_DB_NAME
          value: "carlistingdbci"
        - name: TZ
          value: "Australia/Sydney"
        - name: SPRING_PROFILES_ACTIVE
          value: "ci"     
        - name: CARLISTING_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: carlistingdbpassword
              key: carlistingdbpassword