apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: car-listing-service
  name: car-listing-service
  namespace: carmarketplace-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-listing-service
  template:
    metadata:
      labels:
        app: car-listing-service
    spec:
      containers:
        - name: cm-car-listing-service
          image: geekymon2/cm-car-listing-svc:latest
          env:
          - name: ARTIFACT_NAME
            value: "car-listing-service"
          - name: CARLISTING_DB_NAME
            value: "carlistingdbci"            
          - name: TZ
            value: "Australia/Sydney"
          - name: SPRING_PROFILES_ACTIVE
            value: "ci"
          - name: CARLISTING_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: carlistingdbpassword
                key: carlistingdbpassword
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"