apiVersion: v1
kind: Service
metadata:
  name: car-listing-service
  namespace: carmarketplace-dev
spec:
  selector:
    app: car-listing-service
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081