# For troubleshooting only
apiVersion: v1
kind: Pod
metadata:
  name: api-gateway
  namespace: carmarketplace-dev
spec:
  restartPolicy: Never
  containers:
    - name: api-gateway
      image: geekymon2/cm-apigateway:latest
      command:
        - sleep
        - "8600"
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      env:
        - name: ARTIFACT_NAME
          value: "api-gateway"
        - name: TZ
          value: "Australia/Sydney"
        - name: SPRING_PROFILES_ACTIVE
          value: "ci"