# For troubleshooting only
apiVersion: apps/v1
kind: Pod
metadata:
  name: car-info-service
  namespace: carmarketplace-dev
spec:
  restartPolicy: Never
  containers:
    - name: car-info-service
      image: geekymon2/cm-car-info-svc:latest
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      env:
        - name: ARTIFACT_NAME
          value: "car-info-service"
        - name: CARINFO_DB_NAME
          value: "carinfodbci"
        - name: TZ
          value: "Australia/Sydney"
        - name: SPRING_PROFILES_ACTIVE
          value: "ci"
        - name: CARINFO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: carinfodbpassword
              key: carinfodbpassword
      command:
        - sleep
        - "8600"